import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/Link'
import styles from '../styles/Home.module.css'
import { Select, InputGroup, Input, InputRightElement, Button, VStack, Image, HStack, Text } from '@chakra-ui/react'
import React from 'react'

const Home: NextPage = () => {
  const [show, setShow] = React.useState(false)
  const handleClick = () => setShow(!show)

  return (
    <div className={styles.container}>
      <Head>
        <title>Frosh Funds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <HStack>
          <Image
            height="85vh"
            objectFit="contain"
            src="/vert_gears.png"
            alt="gears"
          />

          <VStack spacing={8} height="100vh" width="50vh" justify="center">
            <Text as="b" fontSize="6xl" color="#0070c4" fontFamily="mono">Frosh Funds</Text>

            <Select placeholder="Select School">
              <option value="UofT">University of Toronto</option>
              <option value="UBC">University of British Columbia</option>
              <option value="UW">University of Waterloo</option>
              <option value="Brock">Brock University</option>
              <option value="McMaster">McMaster University</option>
              <option value="Western">Western University</option>
              <option value="Queen's">Queen's University</option>
              <option value="UofC">University of Calgary</option>
            </Select>

            <Input focusBorderColor="blue.500" placeholder="Username" />

            <InputGroup size="md">
              <Input
                focusBorderColor="blue.500"
                pr="4.5rem"
                type={show ? "text" : "password"}
                placeholder="Enter password"
              />
              <InputRightElement width="4.5rem">
                <Button h="1.75rem" size="sm" onClick={handleClick}>
                  {show ? "Hide" : "Show"}
                </Button>
              </InputRightElement>
            </InputGroup>

            <Button colorScheme="blue">
              <Link href="/students">Submit</Link>
            </Button>
          </VStack>
        </HStack>
      </main>
    </div>
  )
}

export default Home
