import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/Link'
import styles from '../styles/Home.module.css'
import { 
  Select, 
  Button, 
  VStack, 
  Image, 
  HStack, 
  Text, 
  Stack} from '@chakra-ui/react'
import React from 'react'
import { useUser } from '@auth0/nextjs-auth0'

const Home: NextPage = () => {
  const { user, isLoading, error } = useUser()

  if (isLoading) return <div>Loading...</div>
  if (error) return <div>{error.message}</div>

  return (
    <div className={styles.container}>
      <Head>
        <title>Frosh Funds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <HStack>
          <Image
            height="85vh"
            objectFit="contain"
            src="/vert_gears.png"
            alt="gears"
          />

          <VStack spacing={8} height="80vh" width="65vh" justify="center">
            <Text as="b" fontSize="6xl" color="#0070c4" fontFamily="mono">Frosh Funds</Text>

            <Text fontSize="xl" fontFamily="mono">Welcome {user?.name}!</Text>
            
            <Select placeholder="Select School">
              <option value="UofT">University of Toronto</option>
              <option value="UBC">University of British Columbia</option>
              <option value="UW">University of Waterloo</option>
              <option value="Brock">Brock University</option>
              <option value="McMaster">McMaster University</option>
              <option value="Western">Western University</option>
              <option value="Queen's">Queen's University</option>
              <option value="UofC">University of Calgary</option>
            </Select>

            <Stack direction="row" width="100%" color="white" p={5} top="0" justify="center">
              <Button colorScheme="blue">
                <a href="/api/auth/login">Login</a>
              </Button>
              
              <Button colorScheme="blue">
                <a href="/api/auth/logout">Logout</a>
              </Button>
              
              <Button colorScheme="blue">
                <Link href="/students">Search</Link>
              </Button>
            </Stack>

          </VStack>
        </HStack>
      </main>
    </div>
  )
}

export default Home
