import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/Link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Select } from '@chakra-ui/react'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Introduction to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Select placeholder="Select school">
          <option value="UBC">The University of British Columbia</option>
          <option value="UW">University of Waterloo</option>
          <option value="Brock">Brock University</option>
        </Select>

        <Link href="/students">See all Students</Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Matthew
        </a>
      </footer>
    </div>
  )
}

export default Home
