import { Grid } from '@chakra-ui/react'
import axios from 'axios'
import StudentListItem from "../components/StudentListItem"
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'

const Home: NextPage = () => {
  const [customers, setCustomers] = useState<any[]>([])
  console.log("customers:", customers)

  useEffect(() => {
    axios.get("/api/students").then((response) => {
        setCustomers(response.data.customers)
    })
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {customers && <StudentGrid customers={customers} />}
    </div>
  )
}

const StudentGrid = (props: { customers: any[] }) => {
    return (
      <Grid
        templateColumns="repeat(auto-fit, minmax(250px, 1fr));"
        gap={6}
        p={6}
        w="100%"
      >
        {props.customers.map((customer) => (
          <StudentListItem key={customer._id} customer={customer} />
        ))}
      </Grid>
    )
  }

export default Home